version: '3.8'

services:
  hardhat-network:
    build: .
    container_name: escrow-hardhat-network
    ports:
      - "8545:8545"
    environment:
      - NODE_ENV=development
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hardhat-net

networks:
  hardhat-net:
    driver: bridge